version: '3.9'
services:
  app:
    image: url_shortener_image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/app
    ports:
      - "8080:3000"
    depends_on:
      - redis
    environment:
      - TINY_DOMAIN=localhost:8080
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
